# default.yml is the exportable rubocop configuration imported by projects using this gem.
# This file ".rubocop.yml" is used strictly for linting the code in this gem.

inherit_from:
  - default.yml

GLCops/TailwindNoContradictingClassName:
  Enabled: false