require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-magic_numbers
  - ./lib/gl_rubocop/gl_cops/interactor_inherits_from_interactor_base.rb
  - ./lib/gl_rubocop/gl_cops/callback_method_names.rb
  - ./lib/gl_rubocop/gl_cops/prevent_erb_files.rb
  - ./lib/gl_rubocop/gl_cops/sidekiq_inherits_from_sidekiq_job.rb

AllCops:
  SuggestExtensions: false
  NewCops: enable

GLCops/InteractorInheritsFromInteractorBase:
  Enabled: false

GLCops/CallbackMethodNames:
  Enabled: true

GLCops/PreventErbFiles:
  Enabled: true

Layout/LineLength:
  Max: 100
  AllowedPatterns:
    - '^ *#'        # Ignores full lines starting with any indentation and a comment (#)

MagicNumbers/NoAssignment:
  Enabled: false
  AllowedAssignments:
    - instance_variables
    - class_variables
    - global_variables

MagicNumbers/NoArgument: 
  Enabled: true
  PermittedValues:
  - 0
  - 1

MagicNumbers/NoDefault:
  Enabled: true
  PermittedValues:
  - 0
  - 1

MagicNumbers/NoReturn:
  Enabled: true
  PermittedReturnValues:
  - 0
  - 1

Metrics/AbcSize:
  Max: 17

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Performance/MapCompact:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 30

RSpec/AnyInstance:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true

RSpec/MessageSpies:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - staging
    - sandbox
    - production
    - test

Style/HashAsLastArrayItem:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/FilePath:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: true

RSpec/VariableName:
  AllowedPatterns:
    - 'Authorization' # used in RSwag specs

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button

Capybara/NegationMatcher:
  EnforcedStyle: not_to
