require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-magic_numbers
  - rubocop-haml
  - rubocop-rake
  - ./lib/gl_rubocop/gl_cops/interactor_inherits_from_interactor_base.rb
  - ./lib/gl_rubocop/gl_cops/callback_method_names.rb
  - ./lib/gl_rubocop/gl_cops/prevent_erb_files.rb
  - ./lib/gl_rubocop/gl_cops/rails_cache.rb
  - ./lib/gl_rubocop/gl_cops/sidekiq_inherits_from_sidekiq_job.rb
  - ./lib/gl_rubocop/gl_cops/unique_identifier.rb

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "db/**/*"
    - "log/**/*"
    - "public/**/*"
    - "spec/factories/**/*"
    - "spec/support/**/*"
    - "swagger/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"

GLCops/InteractorInheritsFromInteractorBase:
  Enabled: true
  Include:
    - "app/interactors/**/*"

GLCops/CallbackMethodNames:
  Enabled: true

GLCops/PreventErbFiles:
  Enabled: true

GLCops/RailsCache:
  Enabled: true

GLCops/SidekiqInheritsFromSidekiqJob:
  Include:
    - "app/**/*_worker.rb"
    - "app/**/*_job.rb"

GLCops/UniqueIdentifier:
  Enabled: true
  Include:
    - "app/components/**/*.haml"

Layout/ClassStructure:
  Enabled: true
  
Layout/LineLength:
  Max: 100
  AllowedPatterns:
    - "^ *#" # Ignores full lines starting with any indentation and a comment (#)

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*"

MagicNumbers/NoAssignment:
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  Enabled: false
  AllowedAssignments:
    - instance_variables
    - class_variables
    - global_variables

MagicNumbers/NoArgument:
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  Enabled: true
  PermittedValues:
    - 0
    - 1

MagicNumbers/NoDefault:
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  Enabled: true
  PermittedValues:
    - 0
    - 1

MagicNumbers/NoReturn:
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  Enabled: true
  PermittedReturnValues:
    - 0
    - 1

Metrics/AbcSize:
  Max: 17
  Exclude:
    - "db/**/*"
    - "spec/**/*"
    - "config/routes.rb"
    - "config/routes/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "app/mailers/**/*"
    - "config/routes/**/*"
    - "db/**/*"
    - "lib/tasks/**/*"

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "db/**/*"
    - "config/routes/*"
    - "config/coverband.rb"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "db/seeds/**/*"

Metrics/CyclomaticComplexity:
  Exclude:
    - "db/seeds/**/*"

Metrics/PerceivedComplexity:
  Exclude:
    - "db/seeds/**/*"

Metrics/ParameterLists:
  Exclude:
    - "db/seeds/**/*"

Performance/MapCompact:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/ClassAndModuleChildren:
  Exclude:
    - "app/controllers/smart_donations_legacy/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UnusedIgnoredColumns:
  # This rule is incompatible with our split schema for datawarehouse models
  # It is disabled by default in rubocop-rails
  Enabled: false

Style/GlobalVars:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 6
  Exclude:
    - "spec/controllers/**/*"
    - "spec/requests/**/*"

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - "spec/system/**/*"

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - "spec/lib/props_module_spec.rb"
    - "spec/system/**/*"
    - "spec/serializers/**/*"

RSpec/AnyInstance:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"
    - "db/**/*"

RSpec/MessageSpies:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Rails/Output:
  Exclude:
    - "db/seeds/**/*"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/api/**/*"

RSpec/DescribeClass:
  Exclude:
    - "spec/api/**/*"
    - "spec/views/**/*"
    - "spec/lib/tasks/**/*"

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/*"

RSpec/HookArgument:
  Exclude:
    - "spec/support/**/*"

RSpec/InstanceVariable:
  Exclude:
    - "spec/workers/salesforce/**/*"
    - "spec/views/**/*"
    - "spec/services/salesforce/**/*"
    - "spec/controllers/salesforce_controller_spec.rb"
    - "spec/controllers/v1/**/*"

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - loadtesting
    - staging
    - sandbox
    - production
    - test

Style/HashAsLastArrayItem:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: "snake_case"
  AllowedIdentifiers:
    - is_501c3
    - last4
    - line1
    - line2
    - address_line1
    - address_line2
    - google_oauth2
    - s3
    - shift4
    - Shift4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/FilePath:
  Enabled: true
  Exclude:
    - "packs/*/spec/**/*" # Because of automatic namespacing

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - "packs/*/spec/**/*" # Because of automatic namespacing

RSpec/VariableName:
  AllowedPatterns:
    - "Authorization" # used in RSwag specs

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button

Capybara/NegationMatcher:
  EnforcedStyle: not_to
