require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-magic_numbers
  - rubocop-haml
  - rubocop-rake
  - rubocop-sorbet
  - ./lib/gl_rubocop/gl_cops/callback_method_names.rb
  - ./lib/gl_rubocop/gl_cops/interactor_inherits_from_interactor_base.rb
  - ./lib/gl_rubocop/gl_cops/limit_flash_options.rb
  - ./lib/gl_rubocop/gl_cops/no_stubbing_perform_async.rb
  - ./lib/gl_rubocop/gl_cops/prevent_erb_files.rb
  - ./lib/gl_rubocop/gl_cops/rails_cache.rb
  - ./lib/gl_rubocop/gl_cops/sidekiq_inherits_from_sidekiq_job.rb
  - ./lib/gl_rubocop/gl_cops/unique_identifier.rb

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "db/**/*"
    - "log/**/*"
    - "public/**/*"
    - "spec/factories/**/*"
    - "spec/support/**/*"
    - "swagger/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button

Capybara/NegationMatcher:
  EnforcedStyle: not_to

GLCops/CallbackMethodNames:
  Enabled: true

GLCops/InteractorInheritsFromInteractorBase:
  Enabled: true
  Include:
    - "app/interactors/**/*"

GLCops/LimitFlashOptions:
  Enabled: true

GLCops/NoStubbingPerformAsync:
  Enabled: true

GLCops/PreventErbFiles:
  Enabled: true

GLCops/RailsCache:
  Enabled: true

GLCops/SidekiqInheritsFromSidekiqJob:
  Include:
    - "app/**/*_worker.rb"
    - "app/**/*_job.rb"

GLCops/UniqueIdentifier:
  Enabled: true
  Include:
    - "app/components/**/*.haml"

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  AllowedPatterns:
    - "^ *#" # Ignores full lines starting with any indentation and a comment (#)
  Max: 100

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*"

MagicNumbers/NoArgument:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  PermittedValues:
    - 0
    - 1

MagicNumbers/NoAssignment:
  AllowedAssignments:
    - instance_variables
    - class_variables
    - global_variables
  Enabled: false
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"

MagicNumbers/NoDefault:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  PermittedValues:
    - 0
    - 1

MagicNumbers/NoReturn:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "**/spec/**/*"
  PermittedReturnValues:
    - 0
    - 1

Metrics/AbcSize:
  Exclude:
    - "db/**/*"
    - "spec/**/*"
    - "config/routes.rb"
    - "config/routes/*"
  Max: 17

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "db/**/*"
    - "config/routes/*"
    - "config/coverband.rb"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "db/seeds/**/*"
  Max: 150

Metrics/CyclomaticComplexity:
  Exclude:
    - "db/seeds/**/*"

Metrics/MethodLength:
  Exclude:
    - "app/mailers/**/*"
    - "config/routes/**/*"
    - "db/**/*"
    - "lib/tasks/**/*"
  Max: 15

Metrics/ParameterLists:
  Exclude:
    - "db/seeds/**/*"

Metrics/PerceivedComplexity:
  Exclude:
    - "db/seeds/**/*"

Naming/MethodParameterName:
  MinNameLength: 1

Naming/VariableNumber:
  AllowedIdentifiers:
    - is_501c3
    - last4
    - line1
    - line2
    - address_line1
    - address_line2
    - google_oauth2
    - s3
    - shift4
    - Shift4
  EnforcedStyle: "snake_case"

Performance/MapCompact:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/api/**/*"
    - "spec/views/**/*"
    - "spec/lib/tasks/**/*"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/api/**/*"

RSpec/ExampleLength:
  Exclude:
    - "spec/lib/props_module_spec.rb"
    - "spec/system/**/*"
    - "spec/serializers/**/*"
  Max: 30

RSpec/FilePath:
  Enabled: true
  Exclude:
    - "packs/*/spec/**/*" # Because of automatic namespacing

RSpec/HookArgument:
  Exclude:
    - "spec/support/**/*"

RSpec/IndexedLet:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - "spec/workers/salesforce/**/*"
    - "spec/views/**/*"
    - "spec/services/salesforce/**/*"
    - "spec/controllers/salesforce_controller_spec.rb"
    - "spec/controllers/v1/**/*"

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - "spec/system/**/*"
  Max: 8

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - "spec/controllers/**/*"
    - "spec/requests/**/*"
  Max: 6

RSpec/ReceiveMessages:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - "packs/*/spec/**/*" # Because of automatic namespacing

RSpec/VariableName:
  AllowedPatterns:
    - "Authorization" # used in RSwag specs

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true

RSpecRails/InferredSpecType:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/*"

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - "db/seeds/**/*"

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"
    - "db/**/*"

Rails/TimeZone:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - loadtesting
    - staging
    - sandbox
    - production
    - test

Rails/UnusedIgnoredColumns:
  # This rule is incompatible with our split schema for datawarehouse models
  # It is disabled by default in rubocop-rails
  Enabled: false

Sorbet/AllowIncompatibleOverride:
  Enabled: false

Sorbet/BindingConstantWithoutTypeAlias:
  Enabled: false

Sorbet/BuggyObsoleteStrictMemoization:
  Enabled: false

Sorbet/CheckedTrueInSignature:
  Enabled: false

Sorbet/ConstantsFromStrings:
  Enabled: true

Sorbet/EmptyLineAfterSig:
  Enabled: false

Sorbet/EnforceSigilOrder:
  Enabled: false

Sorbet/EnforceSingleSigil:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: false

Sorbet/ForbidComparableTEnum:
  Enabled: false

Sorbet/ForbidExtendTSigHelpersInShims:
  Enabled: false

Sorbet/ForbidRBIOutsideOfAllowedPaths:
  Enabled: false

Sorbet/ForbidUntypedStructProps:
  Enabled: false

Sorbet/KeywordArgumentOrdering:
  Enabled: false

Sorbet/MultipleTEnumValues:
  Enabled: false

Sorbet/ObsoleteStrictMemoization:
  Enabled: false

Sorbet/SelectByIsA:
  Enabled: false

Sorbet/SignatureBuildOrder:
  Enabled: false

Sorbet/TypeAliasName:
  Enabled: false
  
Sorbet/ValidGemVersionAnnotations:
  Enabled: false

Sorbet/ValidSigil:
  Enabled: false

Sorbet/VoidCheckedTests:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - "app/controllers/smart_donations_legacy/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - "spec/**/*"

Style/HashAsLastArrayItem:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false